version: "2"
services:
  app:
    container_name: app
    restart: always
    build: .
    ports:
      - "8888:8888"
    links:
      - mongoDB
  mongoDB:
    image: mongo
    container_name: mongoDB
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"